name: React Frontend CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag your-dockerhub-username/courses-frontend:latest

    - name: Push Docker image
      run: docker push your-dockerhub-username/courses-frontend:latest
